---
name: Nginx Proxy Manager CrowdSec Moded
version: 0.1Alpha
slug: nginxproxymanager
description: Manage Nginx proxy hosts with a simple, powerful interface mo
url: https://github.com/hassio-addons/addon-nginx-proxy-manager
codenotary: codenotary@frenck.dev
webui: http://[HOST]:[PORT:8181]
init: false
arch:
  - aarch64
hassio_api: true
ports:
  8080/tcp: 80
  8181/tcp: 81
  4443/tcp: 443
ports_description:
  8080/tcp: HTTP Entrance port
  8181/tcp: Proxy management web interface
  4443/tcp: HTTPS/SSL Entrance port
map:
  - addon_config:rw
backup_exclude:
  - "*/logs"
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
